---
# Distro specific
- name: Install libvirt and other dependencies
  include_tasks: install-deps/main.yml
  when: 'not only_verify_user|bool'

- name: Enables / verifies if user to run libvirt guests
  include_tasks: enable-user/main.yml
