---
- name: Adds the user to the respective distro libvirt groups
  become: yes
  become_method: sudo
  user:
    name: "{{ ansible_user }}"
    groups: libvirt,kvm,qemu
    append: yes
  when: 'not only_verify_user|bool'

- name: Verifies user's effective group allows to run libvirt/kvm without being root
  shell: groups | grep {{ item }}
  with_items:
    - libvirt
    - kvm
    - qemu
  loop_control:
    label: "Verifying if user's current effective groups includes {{ item }}"
  register: group_check
  failed_when: False
  ignore_errors: true
  when: 'only_verify_user|bool'

- name: Inform if user must log out and back in to use libvirt as a regular user
  register: user_groups_ready
  debug:
    msg: "User group settings are not in effect, you must log out and back in to make group {{ item.item }} be part of your effective group"
  failed_when: item.rc is undefined or item.rc != 0
  when:
    - 'item.rc != 0'
    - 'only_verify_user|bool'
  with_items: "{{ group_check.results }}"
  loop_control:
    label: "Ensure if user's current effective groups includes {{ item.item }}"
  when: 'only_verify_user|bool'
