---
- name: Install libvirt / kvm dependencies
  become: yes
  become_method: sudo
  yum:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - qemu-x86
    state: present

- name: Make sure libvirtd is running
  become: yes
  become_method: sudo
  systemd:
    state: started
    name: libvirtd
