---
- name: Install libvirt / kvm dependencies
  become: yes
  become_method: sudo
  yum:
    name:
      - libvirt
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - qemu-x86
    state: present
